export interface ServiceFeature {
  icon: string;
  title: string;
  description: string;
}

export interface ProcessStep {
  number: string;
  title: string;
  description: string;
  duration: string;
}

export interface PricingTier {
  name: string;
  price: string;
  badge?: string;
  description: string;
  features: string[];
}

export interface FAQ {
  q: string;
  a: string;
}

export interface ServiceData {
  slug: string;
  icon: string;
  label?: string;
  title: string;
  shortDescription: string;
  hero: {
    badge: string;
    tagline: string;
    title: string;
    subtitle: string;
    heroDescription: string;
  };
  problems: {
    heading: string;
    subheading?: string;
    problems: string[];
  };
  features: {
    heading: string;
    description: string;
    features: ServiceFeature[];
  };
  process: {
    heading: string;
    description: string;
    steps: ProcessStep[];
  };
  pricing: {
    heading: string;
    subheading: string;
    tiers: PricingTier[];
  };
  faqs: FAQ[];
  cta: {
    heading: string;
    subheading: string;
    primaryCTA: string;
    primaryLink: string;
    secondaryCTA: string;
    secondaryLink: string;
    note: string;
  };
}

export const servicesData: ServiceData[] = [
  {
    slug: "web-development",
    icon: "Globe",
    label: "Most Popular",
    title: "Web Development",
    shortDescription: "Custom, fast, and stunning websites built with Next.js — designed to convert visitors into clients.",
    hero: {
      badge: "Most Popular Service",
      tagline: "Fast. Modern. Built to Convert.",
      title: "Web Development",
      subtitle: "Your website is your 24/7 salesperson. We build websites that make visitors stay, trust, and hire you.",
      heroDescription: "In today's world, your website is your first impression. It either wins you clients — or sends them straight to your competitors. At Cortex Agents, we build websites that are blazing fast, visually stunning, and engineered to convert.",
    },
    problems: {
      heading: "Is Your Current Website Costing You Clients?",
      subheading: "If any of these feel familiar, you're losing money every day:",
      problems: [
        "Your website looks outdated — visitors leave within 5 seconds without reading anything",
        "It loads slowly, especially on mobile — 53% of users abandon sites that take over 3 seconds",
        "No clear direction — visitors don't know what to do next, so they do nothing",
        "Your competitor's website looks more professional — and they're getting your customers",
        "You're not showing up on Google — your ideal clients can't even find you",
        "The design doesn't reflect the quality of your actual work — you're underselling yourself",
      ],
    },
    features: {
      heading: "What We Deliver",
      description: "Every website is custom-built from scratch — no templates, no page builders. We use Next.js and Tailwind CSS so your site is fast, modern, and built to last.",
      features: [
        {
          icon: "Zap",
          title: "Lightning Fast Performance",
          description: "We build with Next.js — the framework trusted by Netflix, TikTok, and thousands of top companies. Your site loads in under 2 seconds, ranks higher on Google, and keeps visitors from bouncing.",
        },
        {
          icon: "Smartphone",
          title: "Flawless on Every Device",
          description: "Over 60% of your visitors are on mobile. Every pixel is tested on iPhone SE, Android, iPad, and widescreen desktop. No broken layouts, no hidden text, no overflow buttons — ever.",
        },
        {
          icon: "Palette",
          title: "Design That Builds Trust Instantly",
          description: "First impressions happen in 0.05 seconds. Our designs are modern, clean, and conversion-focused — so visitors trust you before they even read a word.",
        },
        {
          icon: "Search",
          title: "SEO-Ready From Day One",
          description: "Proper meta tags, semantic HTML, blazing speed, structured data, and a sitemap — all built in. Your site is ready to rank the moment it goes live.",
        },
        {
          icon: "Code",
          title: "Clean, Scalable Code",
          description: "Every line of code is written by our developers — not generated by page builders. That means easy updates, fast performance, and a site that grows with your business.",
        },
        {
          icon: "Shield",
          title: "Secure & Reliable",
          description: "HTTPS, secure APIs, environment variable protection, and regular deployment checks. Your website and your visitors' data are always protected.",
        },
      ],
    },
    process: {
      heading: "How We Build Your Website",
      description: "A clear, collaborative process — so you always know what's happening.",
      steps: [
        {
          number: "01",
          title: "Discovery Call",
          description: "We start with a free 30-minute call to understand your business, your goals, and your target audience. No jargon — just a real conversation.",
          duration: "Day 1",
        },
        {
          number: "02",
          title: "Design Mockup",
          description: "We design the full website in Figma first — so you can see exactly how it will look before a single line of code is written. You request changes freely.",
          duration: "Day 2–4",
        },
        {
          number: "03",
          title: "Development",
          description: "Once design is approved, our developers build the full site in Next.js. Clean code, fast performance, mobile-first from the ground up.",
          duration: "Day 5–12",
        },
        {
          number: "04",
          title: "Review & Revisions",
          description: "We share a live preview link. You review every page and request any changes. We revise until you are 100% satisfied — no extra charges.",
          duration: "Day 13–15",
        },
        {
          number: "05",
          title: "Launch & Handover",
          description: "We deploy your site, connect your domain, set up analytics, and hand over everything. You own your website completely.",
          duration: "Day 16",
        },
      ],
    },
    pricing: {
      heading: "Simple, Transparent Pricing",
      subheading: "No hidden fees. No surprises. Just great work.",
      tiers: [
        {
          name: "Starter",
          price: "PKR 25,000",
          description: "Perfect for freelancers, consultants, and small businesses.",
          features: [
            "Up to 5 pages",
            "Mobile responsive",
            "Contact form",
            "Basic SEO setup",
            "2 rounds of revisions",
            "Delivered in 7 days",
          ],
        },
        {
          name: "Professional",
          price: "PKR 55,000",
          badge: "Most Popular",
          description: "For growing businesses that want to stand out.",
          features: [
            "Up to 10 pages",
            "Custom animations (Framer Motion)",
            "Blog or portfolio section",
            "Advanced SEO setup",
            "WhatsApp chat integration",
            "3 rounds of revisions",
            "Delivered in 14 days",
          ],
        },
        {
          name: "Premium",
          price: "Custom",
          description: "For businesses that want the best — no compromises.",
          features: [
            "Unlimited pages",
            "3D animations & interactions",
            "CMS integration (Sanity/Contentful)",
            "Full SEO + analytics setup",
            "Performance optimization",
            "Priority support",
            "Custom timeline",
          ],
        },
      ],
    },
    faqs: [
      {
        q: "How long does it take to build a website?",
        a: "A standard 5–10 page website takes 7–14 days. Larger or more complex projects may take 3–4 weeks. We always give you a clear timeline upfront.",
      },
      {
        q: "Do I need to provide content and images?",
        a: "You can provide your own content and images, or we can help write copy and source royalty-free visuals. We guide you through the whole process.",
      },
      {
        q: "Will I be able to update the website myself?",
        a: "Yes. We can integrate a CMS (like Sanity or Contentful) so you can update text, images, and blog posts yourself — no coding needed.",
      },
      {
        q: "What if I don't like the design?",
        a: "We show you a full design mockup before writing any code. You request changes freely. We don't start development until you are happy with the design.",
      },
      {
        q: "Do you offer hosting?",
        a: "We deploy on Vercel (the fastest hosting for Next.js websites). Vercel's free tier covers most small websites. We walk you through everything at launch.",
      },
    ],
    cta: {
      heading: "Ready to Get a Website That Actually Works?",
      subheading: "Let's build something you're proud to share.",
      primaryCTA: "Start My Project",
      primaryLink: "/contact",
      secondaryCTA: "WhatsApp Us Now",
      secondaryLink: "https://wa.me/923212322687",
      note: "Free consultation call • No commitment required • Reply within 2 hours",
    },
  },
  {
    slug: "ui-ux-design",
    icon: "Layers",
    title: "UI/UX Design",
    shortDescription: "Beautiful, intuitive designs that users love and businesses profit from — built in Figma.",
    hero: {
      badge: "Design That Converts",
      tagline: "Design Isn't Decoration. It's Strategy.",
      title: "UI/UX Design",
      subtitle: "Beautiful interfaces that feel effortless to use — because great design is invisible, but its results aren't.",
      heroDescription: "Bad design is expensive. It confuses users, kills conversions, and destroys trust. Great design does the opposite — it guides people exactly where you want them, builds confidence in your brand, and turns visitors into loyal customers.",
    },
    problems: {
      heading: "Signs Your Design Is Hurting Your Business",
      problems: [
        "Users can't figure out how to navigate your app or website — they leave frustrated",
        "Your product looks outdated — users assume the quality of your service matches your design",
        "Low conversion rates — people visit but don't buy, sign up, or contact you",
        "Inconsistent branding — your app, website, and social media all look like different companies",
        "You've had negative feedback about how confusing the product is to use",
        "Your competitors have a slicker, more modern interface — and you're losing business to them",
      ],
    },
    features: {
      heading: "Our Design Services",
      description: "",
      features: [
        {
          icon: "Layout",
          title: "Website & Landing Page Design",
          description: "High-converting page designs that guide visitors from curious to convinced. Every element is placed with purpose — nothing is decorative without being functional.",
        },
        {
          icon: "Pen",
          title: "Figma UI Design",
          description: "We design in Figma — the industry standard. You get fully organized, component-based design files that developers love to work with and you can easily update.",
        },
        {
          icon: "Smartphone",
          title: "Mobile App UI Design",
          description: "Thumb-friendly, platform-aware mobile interfaces that feel native. We follow iOS and Android design guidelines so users feel at home instantly.",
        },
        {
          icon: "RefreshCw",
          title: "Redesign & Revamp",
          description: "Have an existing product that needs a refresh? We analyze what's not working, redesign with purpose, and give your product a modern, competitive look.",
        },
        {
          icon: "Users",
          title: "User Research & Wireframing",
          description: "Before designing anything beautiful, we make sure it makes sense. We map out user journeys, create wireframes, and validate the flow before adding visuals.",
        },
        {
          icon: "Sparkles",
          title: "Design Systems & Brand Identity",
          description: "Consistent colors, typography, spacing, and components across your entire product. One design language that ties everything together beautifully.",
        },
      ],
    },
    process: {
      heading: "How We Design Your Product",
      description: "A clear, collaborative process — so you always know what's happening.",
      steps: [
        {
          number: "01",
          title: "Discovery & Research",
          description: "We learn your business, your users, your competitors, and your goals. We audit your current design and identify exactly what to fix and improve.",
          duration: "Day 1–2",
        },
        {
          number: "02",
          title: "Wireframes",
          description: "Low-fidelity wireframes that map the structure and flow. We finalize the layout and user journey before adding any visual design.",
          duration: "Day 3–5",
        },
        {
          number: "03",
          title: "Visual Design",
          description: "We apply your brand identity — colors, typography, icons, imagery — to create stunning high-fidelity mockups in Figma.",
          duration: "Day 6–10",
        },
        {
          number: "04",
          title: "Prototype & Review",
          description: "We create an interactive Figma prototype you can click through — just like the real product. You test it, give feedback, and we refine.",
          duration: "Day 11–13",
        },
        {
          number: "05",
          title: "Handoff",
          description: "You receive fully organized Figma files, exported assets, and a design system. Ready for developers to build immediately.",
          duration: "Day 14",
        },
      ],
    },
    pricing: {
      heading: "Simple, Transparent Pricing",
      subheading: "No hidden fees. No surprises. Just great work.",
      tiers: [
        {
          name: "Landing Page",
          price: "PKR 15,000",
          description: "One powerful, conversion-focused page design.",
          features: [
            "Single page Figma design",
            "Desktop + mobile versions",
            "2 revisions",
            "Exported assets included",
          ],
        },
        {
          name: "Full Website",
          price: "PKR 35,000",
          badge: "Most Popular",
          description: "Complete website UI design, ready for development.",
          features: [
            "Up to 8 pages",
            "Desktop + mobile + tablet",
            "Component library in Figma",
            "3 revisions",
            "Developer handoff ready",
          ],
        },
        {
          name: "Product / App Design",
          price: "Custom",
          description: "Full product UI/UX including research, wireframes, and design system.",
          features: [
            "User research & journey mapping",
            "Wireframes + high-fidelity design",
            "Interactive prototype",
            "Full design system",
            "Unlimited revisions",
            "Ongoing design support",
          ],
        },
      ],
    },
    faqs: [
      {
        q: "What do I need to provide to get started?",
        a: "Just your brand colors and logo if you have them, some reference websites you like, and a brief about your business. We handle the rest.",
      },
      {
        q: "Do you also develop the design you create?",
        a: "Yes! Most clients hire us for both design and development. It's faster, cheaper, and results in a pixel-perfect final product since the same team handles both.",
      },
      {
        q: "How many revisions do I get?",
        a: "The number of revisions depends on your plan, but we work with you until the design is right. We've never delivered a design a client wasn't happy with.",
      },
      {
        q: "Will I own the Figma files?",
        a: "Absolutely. Upon completion, the fully organized Figma file is yours. You can share it with any developer or make edits yourself.",
      },
    ],
    cta: {
      heading: "Let's Design Something Users Actually Love",
      subheading: "Great design pays for itself in conversions, trust, and retention.",
      primaryCTA: "Start Design Project",
      primaryLink: "/contact",
      secondaryCTA: "WhatsApp Us",
      secondaryLink: "https://wa.me/923212322687",
      note: "Free design consultation • See our portfolio first • No commitment",
    },
  },
  {
    slug: "ai-chatbots",
    icon: "MessageSquare",
    label: "AI Powered",
    title: "AI Chatbots",
    shortDescription: "Intelligent chatbots that answer, qualify, and convert your customers — 24/7, automatically.",
    hero: {
      badge: "AI-Powered",
      tagline: "Never Miss a Customer Again.",
      title: "AI Chatbots",
      subtitle: "Your business answers every question, qualifies every lead, and books every appointment — even at 3am while you sleep.",
      heroDescription: "Your customers have questions right now. If they can't get answers instantly, they go to your competitor who does. An AI chatbot built by Cortex Agents means your business is always online, always helpful, and always converting.",
    },
    problems: {
      heading: "You're Losing Customers Right Now",
      problems: [
        "Customers message you at night or on weekends — no reply means no sale",
        "Your team spends hours answering the same 10 questions every single day",
        "Leads go cold because follow-up takes too long — they already moved on",
        "You have no way to qualify leads automatically — wasting time on wrong people",
        "Customers feel ignored — slow response time kills trust before you even meet them",
        "Your competitors have chatbots — they respond instantly, you respond hours later",
      ],
    },
    features: {
      heading: "What Our AI Chatbots Can Do",
      description: "We build custom AI chatbots using the latest language models — not generic rule-based bots with limited menus. Real AI that understands natural language and gives smart, human-like responses.",
      features: [
        {
          icon: "Clock",
          title: "24/7 Customer Support",
          description: "Your chatbot handles customer queries around the clock — product questions, service info, pricing, availability — all answered instantly, any time of day or night.",
        },
        {
          icon: "Filter",
          title: "Automatic Lead Qualification",
          description: "The chatbot asks the right questions, filters serious buyers from browsers, and sends you only qualified leads — so your sales team focuses on closing, not sorting.",
        },
        {
          icon: "Calendar",
          title: "Appointment Booking",
          description: "Clients can book appointments, consultations, or demos directly inside the chat — connected to your calendar. Zero back-and-forth emails.",
        },
        {
          icon: "Globe",
          title: "Multilingual Support",
          description: "Serve customers in Urdu, English, Arabic, or any language. Your chatbot speaks your customer's language — literally.",
        },
        {
          icon: "Database",
          title: "Trained on Your Business Data",
          description: "We train the chatbot on your website, product catalog, FAQs, and business documents. It knows your business inside out — no generic, irrelevant responses.",
        },
        {
          icon: "Link",
          title: "Integrates With Your Tools",
          description: "Connect with WhatsApp, Facebook Messenger, your website, CRM, Google Sheets, email, and more. Your chatbot works inside the platforms your customers already use.",
        },
      ],
    },
    process: {
      heading: "How We Build Your Chatbot",
      description: "A clear, collaborative process — so you always know what's happening.",
      steps: [
        {
          number: "01",
          title: "Business Analysis",
          description: "We learn your business, your most common customer questions, your sales process, and your goals for the chatbot.",
          duration: "Day 1",
        },
        {
          number: "02",
          title: "Chatbot Design",
          description: "We map out the conversation flows — what the bot asks, how it responds to different situations, when it escalates to a human.",
          duration: "Day 2–3",
        },
        {
          number: "03",
          title: "Training & Development",
          description: "We feed the AI your business data — website content, FAQs, product info, pricing — and train it to respond accurately and naturally.",
          duration: "Day 4–8",
        },
        {
          number: "04",
          title: "Testing",
          description: "We test hundreds of conversations — edge cases, tricky questions, wrong inputs — until the chatbot handles everything smoothly.",
          duration: "Day 9–11",
        },
        {
          number: "05",
          title: "Deployment & Integration",
          description: "We embed the chatbot on your website and/or connect it to WhatsApp, Messenger, or any platform. We monitor the first week and fine-tune.",
          duration: "Day 12–14",
        },
      ],
    },
    pricing: {
      heading: "Simple, Transparent Pricing",
      subheading: "No hidden fees. No surprises. Just great work.",
      tiers: [
        {
          name: "Basic Bot",
          price: "PKR 30,000",
          description: "Simple FAQ and support chatbot for your website.",
          features: [
            "Website chat widget",
            "Up to 50 trained Q&As",
            "Lead capture form inside chat",
            "Email notification on new leads",
            "1 month free support",
          ],
        },
        {
          name: "Smart Bot",
          price: "PKR 65,000",
          badge: "Most Popular",
          description: "AI-powered chatbot with lead qualification and integrations.",
          features: [
            "Website + WhatsApp integration",
            "Trained on your full business data",
            "Lead qualification flow",
            "Appointment booking",
            "CRM/Google Sheets integration",
            "Multilingual (Urdu + English)",
            "3 months support",
          ],
        },
        {
          name: "Enterprise Bot",
          price: "Custom",
          description: "Full-scale AI assistant for complex business needs.",
          features: [
            "All Smart Bot features",
            "Custom AI model fine-tuning",
            "Multiple platform integrations",
            "Analytics dashboard",
            "Human handoff system",
            "Ongoing training & improvement",
            "Dedicated support",
          ],
        },
      ],
    },
    faqs: [
      {
        q: "Is this a real AI chatbot or just buttons and menus?",
        a: "Real AI. We use large language models (like GPT-4) that understand natural language. Customers type freely — the bot understands context and responds intelligently, not with limited menu options.",
      },
      {
        q: "Can the chatbot speak Urdu?",
        a: "Yes. We can configure the chatbot to respond in Urdu, English, or both — automatically detecting what language the customer writes in.",
      },
      {
        q: "What happens when the chatbot doesn't know an answer?",
        a: "We set it up to gracefully say it doesn't know and either collect the question for you to answer later, or instantly escalate to a human team member via WhatsApp or email.",
      },
      {
        q: "Does it work on WhatsApp?",
        a: "Yes. We can deploy the chatbot directly on WhatsApp Business using the official API — so customers chat with your AI on the app they already use every day.",
      },
      {
        q: "How long does it take to build?",
        a: "A basic chatbot takes about 7 days. A full AI-powered bot with integrations takes 2–3 weeks. We give you a clear timeline before starting.",
      },
    ],
    cta: {
      heading: "Your Business Deserves to Never Sleep",
      subheading: "Let an AI chatbot handle the questions — you focus on the work.",
      primaryCTA: "Build My Chatbot",
      primaryLink: "/contact",
      secondaryCTA: "WhatsApp Us",
      secondaryLink: "https://wa.me/923212322687",
      note: "Free consultation • See a live demo • Setup in 2 weeks",
    },
  },
  {
    slug: "ai-agents",
    icon: "Bot",
    label: "Cutting Edge",
    title: "AI Agents & Automation",
    shortDescription: "Intelligent AI agents that think, decide, and act — automating complex business workflows end to end.",
    hero: {
      badge: "Next-Level AI",
      tagline: "Stop Doing Repetitive Work. Let AI Do It.",
      title: "AI Agents & Automation",
      subtitle: "AI agents that don't just chat — they take action. Research, process, decide, execute — all without human intervention.",
      heroDescription: "A chatbot answers questions. An AI agent actually does things. It can browse the web, read documents, send emails, update spreadsheets, book meetings, process orders, and execute multi-step tasks — all on its own. This is the future of business operations, and we build it for you today.",
    },
    problems: {
      heading: "Is Your Team Drowning in Manual Work?",
      problems: [
        "Your team spends hours every day on repetitive tasks that should be automated",
        "Data entry errors cost you time, money, and client trust",
        "Following up with leads manually means some always fall through the cracks",
        "Generating reports, invoices, or summaries takes hours — it should take seconds",
        "Your team can't scale — more clients means more manual work, linearly",
        "Competitors using AI are operating at 10x efficiency — you're falling behind",
      ],
    },
    features: {
      heading: "What AI Agents Can Automate for You",
      description: "We build custom AI agents using OpenAI Agent SDK, LangChain, and AgentKit. These agents don't just respond — they reason through tasks, use tools, and complete complex workflows autonomously.",
      features: [
        {
          icon: "Search",
          title: "Research & Data Collection Agents",
          description: "Send your agent a topic, a list of companies, or a set of keywords — it browses the web, reads pages, extracts information, and delivers a structured report. Hours of research done in minutes.",
        },
        {
          icon: "Mail",
          title: "Outreach & Follow-Up Agents",
          description: "The agent monitors your leads, sends personalized follow-up emails at the right time, tracks replies, and updates your CRM — all automatically. No lead ever goes cold again.",
        },
        {
          icon: "FileText",
          title: "Document Processing Agents",
          description: "Upload invoices, contracts, forms, or PDFs — the agent reads them, extracts key data, fills in your spreadsheet or database, and flags anything that needs attention.",
        },
        {
          icon: "BarChart",
          title: "Reporting & Analytics Agents",
          description: "Your agent pulls data from multiple sources, generates weekly or monthly reports, creates summaries, and sends them to you or your team — on schedule, automatically.",
        },
        {
          icon: "GitBranch",
          title: "Multi-Step Workflow Automation",
          description: "Chain complex tasks together: receive a form submission → qualify the lead → send a welcome email → book a call → notify your team → update your CRM. One trigger, ten actions.",
        },
        {
          icon: "Plug",
          title: "API & Tool Integration",
          description: "Connect your AI agent to any tool — Google Sheets, Notion, Slack, WhatsApp, Gmail, Calendly, Airtable, and hundreds more. Your agent works inside your existing stack.",
        },
      ],
    },
    process: {
      heading: "How We Build Your AI Agent",
      description: "A clear, collaborative process — so you always know what's happening.",
      steps: [
        {
          number: "01",
          title: "Workflow Mapping",
          description: "We sit with you and map every manual task you want automated — inputs, outputs, decisions, and edge cases. We identify exactly where AI saves the most time.",
          duration: "Day 1–2",
        },
        {
          number: "02",
          title: "Agent Architecture",
          description: "We design the agent's brain — which tools it uses, how it makes decisions, what it does when something unexpected happens, and how it reports back to you.",
          duration: "Day 3–5",
        },
        {
          number: "03",
          title: "Development & Integration",
          description: "We build the agent using OpenAI Agent SDK and connect it to all required tools and APIs. Every integration is tested thoroughly before moving on.",
          duration: "Day 6–14",
        },
        {
          number: "04",
          title: "Testing & Validation",
          description: "We run the agent through real scenarios — normal cases, edge cases, failures. We ensure it handles everything correctly and reports errors when needed.",
          duration: "Day 15–17",
        },
        {
          number: "05",
          title: "Deployment & Monitoring",
          description: "The agent goes live. We monitor it closely for the first two weeks, fix any unexpected behavior, and hand you a dashboard to track its activity.",
          duration: "Day 18–21",
        },
      ],
    },
    pricing: {
      heading: "Simple, Transparent Pricing",
      subheading: "No hidden fees. No surprises. Just great work.",
      tiers: [
        {
          name: "Single Agent",
          price: "PKR 50,000",
          description: "One focused AI agent for a specific task or workflow.",
          features: [
            "One custom AI agent",
            "Up to 3 tool integrations",
            "Basic monitoring dashboard",
            "1 month support & fixes",
            "Full source code ownership",
          ],
        },
        {
          name: "Automation Suite",
          price: "PKR 120,000",
          badge: "Best Value",
          description: "Multiple agents working together across your business.",
          features: [
            "Up to 3 AI agents",
            "Up to 10 tool integrations",
            "Multi-step workflow automation",
            "Analytics & activity logging",
            "Error alerts & fallback handling",
            "3 months support",
            "Team training included",
          ],
        },
        {
          name: "Enterprise AI",
          price: "Custom",
          description: "Full-scale AI automation for complex business operations.",
          features: [
            "Unlimited agents & workflows",
            "Custom AI model fine-tuning",
            "Enterprise tool integrations",
            "Dedicated monitoring system",
            "Ongoing optimization",
            "SLA-backed support",
            "Quarterly review & improvements",
          ],
        },
      ],
    },
    faqs: [
      {
        q: "What's the difference between a chatbot and an AI agent?",
        a: "A chatbot responds to messages. An AI agent actually does things — it can browse websites, read files, send emails, update databases, and complete multi-step tasks without human input. Think of it as an employee that never sleeps.",
      },
      {
        q: "What tools can AI agents connect to?",
        a: "Almost anything with an API — Gmail, Google Sheets, Notion, Slack, WhatsApp, Airtable, HubSpot, Calendly, Trello, and hundreds more. If your tool has an API, we can connect to it.",
      },
      {
        q: "Is my business data safe with AI agents?",
        a: "Yes. We use secure API connections, never store sensitive data unnecessarily, and follow best practices for handling business information. You control what data the agent can access.",
      },
      {
        q: "What if the agent makes a mistake?",
        a: "We build in validation steps, error handling, and human-in-the-loop checkpoints for critical decisions. The agent can flag uncertain situations for human review instead of acting on them.",
      },
      {
        q: "How much time will this actually save us?",
        a: "Most of our clients save 15–30 hours per week after deploying AI agents. The exact number depends on your workflows — we calculate this with you during the discovery phase.",
      },
    ],
    cta: {
      heading: "Ready to Run Your Business on Autopilot?",
      subheading: "Stop paying people to do what AI can do better, faster, and cheaper.",
      primaryCTA: "Automate My Business",
      primaryLink: "/contact",
      secondaryCTA: "WhatsApp Us",
      secondaryLink: "https://wa.me/923212322687",
      note: "Free workflow audit • See ROI estimate before we start • No lock-in contracts",
    },
  },
  {
    slug: "seo-optimization",
    icon: "TrendingUp",
    title: "SEO Optimization",
    shortDescription: "Rank higher on Google, get found by the right people, and turn organic traffic into real revenue.",
    hero: {
      badge: "Rank Higher. Grow Faster.",
      tagline: "If You're Not on Page 1, You Don't Exist.",
      title: "SEO Optimization",
      subtitle: "We get your website ranking on Google so your ideal clients find you — not your competitors.",
      heroDescription: "93% of online experiences begin with a search engine. If your business isn't showing up on the first page of Google, you're invisible to thousands of potential clients every single month. SEO is not optional anymore — it's your most powerful marketing channel.",
    },
    problems: {
      heading: "Why Your Website Isn't Getting Traffic",
      problems: [
        "You built a great website but nobody visits it — it's invisible on Google",
        "You're spending on ads but the moment you stop paying, all traffic disappears",
        "Your competitors rank above you for every keyword that matters to your business",
        "Your website was never set up with SEO in mind — wrong structure, slow speed, no keywords",
        "You don't know which keywords your customers are actually searching for",
        "No backlinks, no domain authority — Google doesn't trust your site yet",
      ],
    },
    features: {
      heading: "Our SEO Services",
      description: "We take a technical, data-driven approach to SEO — no guesswork, no black-hat tricks. Just proven strategies that build lasting organic traffic.",
      features: [
        {
          icon: "Search",
          title: "Keyword Research & Strategy",
          description: "We find exactly what your ideal customers are searching for — the words, phrases, and questions. Then we build a strategy to rank for the terms that bring paying clients, not just traffic.",
        },
        {
          icon: "Code",
          title: "Technical SEO Audit & Fixes",
          description: "We audit your entire website — page speed, crawlability, indexing issues, broken links, duplicate content, mobile performance — and fix everything that's holding you back.",
        },
        {
          icon: "FileText",
          title: "On-Page SEO Optimization",
          description: "Every page gets optimized — title tags, meta descriptions, header hierarchy, image alt text, internal linking, URL structure, and content optimization for target keywords.",
        },
        {
          icon: "Link",
          title: "Link Building & Authority",
          description: "We build high-quality backlinks from relevant, trusted websites. More quality backlinks = more trust from Google = higher rankings for your business.",
        },
        {
          icon: "BarChart",
          title: "SEO Reporting & Analytics",
          description: "You get monthly reports showing keyword rankings, organic traffic, conversion rates, and what we're doing next. Full transparency — you always know where you stand.",
        },
        {
          icon: "MapPin",
          title: "Local SEO (Karachi & Pakistan)",
          description: "Rank for local searches like 'web agency in Karachi' or 'AI chatbot company Pakistan'. We optimize your Google Business Profile and local citations to dominate local results.",
        },
      ],
    },
    process: {
      heading: "How We Optimize Your Website",
      description: "A clear, collaborative process — so you always know what's happening.",
      steps: [
        {
          number: "01",
          title: "Full SEO Audit",
          description: "We analyze your current website — technical issues, existing rankings, backlinks, speed, and content. This gives us a clear picture of where you are and what needs fixing.",
          duration: "Week 1",
        },
        {
          number: "02",
          title: "Keyword & Competitor Research",
          description: "We find the exact keywords your clients search for and analyze what your top competitors are doing to rank. We identify your fastest path to page 1.",
          duration: "Week 1–2",
        },
        {
          number: "03",
          title: "Technical Fixes",
          description: "We fix all technical SEO issues — site speed, crawl errors, mobile issues, URL structure, schema markup, and anything else Google penalizes you for.",
          duration: "Week 2–3",
        },
        {
          number: "04",
          title: "On-Page Optimization",
          description: "We optimize every page for its target keyword — titles, content, structure, internal links. We also create new SEO content where needed.",
          duration: "Week 3–5",
        },
        {
          number: "05",
          title: "Link Building & Monitoring",
          description: "We build quality backlinks and monitor your rankings weekly. SEO takes 3–6 months to show full results — we send you monthly reports showing progress.",
          duration: "Ongoing",
        },
      ],
    },
    pricing: {
      heading: "Simple, Transparent Pricing",
      subheading: "No hidden fees. No surprises. Just great work.",
      tiers: [
        {
          name: "SEO Starter",
          price: "PKR 20,000 / month",
          description: "For businesses new to SEO that want to start ranking.",
          features: [
            "Full initial audit",
            "Up to 10 keywords targeted",
            "On-page optimization (5 pages)",
            "Monthly ranking report",
            "Google Search Console setup",
            "3 month minimum",
          ],
        },
        {
          name: "SEO Growth",
          price: "PKR 40,000 / month",
          badge: "Recommended",
          description: "For businesses serious about dominating their niche.",
          features: [
            "Everything in Starter",
            "Up to 30 keywords",
            "Full site on-page optimization",
            "4 backlinks per month",
            "Local SEO optimization",
            "Competitor tracking",
            "Monthly strategy call",
            "3 month minimum",
          ],
        },
        {
          name: "SEO Domination",
          price: "Custom",
          description: "For businesses that want to own page 1 completely.",
          features: [
            "Everything in Growth",
            "Unlimited keywords",
            "SEO content creation (blog posts)",
            "Aggressive link building",
            "Technical SEO ongoing maintenance",
            "Weekly reporting",
            "Dedicated SEO strategist",
          ],
        },
      ],
    },
    faqs: [
      {
        q: "How long does SEO take to show results?",
        a: "SEO is a long-term investment. Most clients see meaningful improvement in 3–4 months, with significant results by 6 months. We show you progress reports every month so you can track exactly what's improving.",
      },
      {
        q: "Is SEO better than running Google Ads?",
        a: "Both have their place. Ads give instant traffic but cost money every day and stop the moment you stop paying. SEO builds organic traffic that's free and grows over time. Long term, SEO almost always gives better ROI.",
      },
      {
        q: "Do you guarantee first page rankings?",
        a: "No ethical SEO agency can guarantee specific rankings — Google's algorithm is complex and constantly changing. What we guarantee is professional work, proven strategies, and transparent reporting of real progress.",
      },
      {
        q: "Will my rankings drop if I stop SEO?",
        a: "Gradually, yes — competitors who keep optimizing will outrank you over time. That's why SEO is an ongoing investment, not a one-time fix.",
      },
      {
        q: "Do you do SEO for Urdu-language or Pakistan-specific searches?",
        a: "Absolutely. We specialize in local Pakistani SEO and understand the search behavior of Pakistani audiences — in both English and Urdu.",
      },
    ],
    cta: {
      heading: "Start Showing Up Where Your Clients Are Searching",
      subheading: "Every day you wait, your competitors get more traffic, more leads, more sales.",
      primaryCTA: "Start SEO Today",
      primaryLink: "/contact",
      secondaryCTA: "WhatsApp Us",
      secondaryLink: "https://wa.me/923212322687",
      note: "Free SEO audit included • Month-by-month contracts available • Results tracked transparently",
    },
  },
  {
    slug: "cloud-solutions",
    icon: "Cloud",
    title: "Cloud Solutions",
    shortDescription: "Scalable, secure cloud infrastructure that grows with your business — deployed and managed by experts.",
    hero: {
      badge: "Scale Without Limits",
      tagline: "Your Infrastructure Should Never Hold You Back.",
      title: "Cloud Solutions",
      subtitle: "Modern cloud infrastructure that's fast, secure, scalable, and always online — so your business never goes down.",
      heroDescription: "Whether you're launching a new product, experiencing rapid growth, or struggling with slow, unreliable hosting — we architect and deploy cloud solutions that handle whatever your business throws at them. Built on AWS, Vercel, and modern DevOps practices.",
    },
    problems: {
      heading: "Is Your Infrastructure Slowing You Down?",
      problems: [
        "Your website or app goes down during traffic spikes — you lose customers and credibility",
        "Shared hosting is slow, unreliable, and you've outgrown it",
        "Deployments are manual and stressful — one mistake breaks everything",
        "No backups, no monitoring — you only find out something broke when a client calls",
        "Your app is slow in production even though it works fine locally",
        "You're paying for servers you don't understand and can't manage efficiently",
      ],
    },
    features: {
      heading: "Our Cloud Services",
      description: "We architect, deploy, and manage cloud infrastructure on AWS, Vercel, and other leading platforms — so your team can focus on building products, not fighting servers.",
      features: [
        {
          icon: "Server",
          title: "Cloud Deployment & Hosting",
          description: "We deploy your application on the right platform — Vercel for Next.js, AWS EC2 for custom backends, S3 for storage, RDS for databases. Optimized for performance and cost.",
        },
        {
          icon: "GitBranch",
          title: "CI/CD Pipeline Setup",
          description: "Automated deployment pipelines using GitHub Actions or Vercel. Every code push is automatically tested, built, and deployed — safely, reliably, and without manual steps.",
        },
        {
          icon: "Shield",
          title: "Security & SSL Configuration",
          description: "HTTPS everywhere, environment variable management, IAM roles, firewall rules, and security best practices — your infrastructure is locked down from day one.",
        },
        {
          icon: "Activity",
          title: "Monitoring & Alerting",
          description: "Real-time monitoring of uptime, performance, errors, and resource usage. You get alerts before users notice problems — and we fix issues before they affect your business.",
        },
        {
          icon: "Database",
          title: "Database Setup & Management",
          description: "Managed databases (PostgreSQL, MongoDB, MySQL) with automated backups, read replicas for performance, and proper indexing. Your data is always safe and fast.",
        },
        {
          icon: "TrendingUp",
          title: "Auto-Scaling Infrastructure",
          description: "Your app handles 10 users or 10,000 users without breaking a sweat. We configure auto-scaling so your infrastructure grows automatically with your traffic.",
        },
      ],
    },
    process: {
      heading: "How We Set Up Your Cloud",
      description: "A clear, collaborative process — so you always know what's happening.",
      steps: [
        {
          number: "01",
          title: "Infrastructure Audit",
          description: "We review your current setup — hosting, deployments, databases, security, performance. We identify what's working, what's not, and the fastest path to improvement.",
          duration: "Day 1–2",
        },
        {
          number: "02",
          title: "Architecture Planning",
          description: "We design your target infrastructure — which cloud services to use, how they connect, security setup, and cost estimate. You approve before we touch anything.",
          duration: "Day 3–4",
        },
        {
          number: "03",
          title: "Setup & Migration",
          description: "We set up all cloud services, migrate your application and data (with zero downtime when possible), and configure everything properly.",
          duration: "Day 5–10",
        },
        {
          number: "04",
          title: "CI/CD & Automation",
          description: "We set up automated deployment pipelines, testing, and monitoring. From now on, deploying your app is one click — or fully automatic.",
          duration: "Day 11–13",
        },
        {
          number: "05",
          title: "Handover & Documentation",
          description: "We hand over full access, document everything clearly, and train your team. You're never dependent on us — but we're always available when needed.",
          duration: "Day 14",
        },
      ],
    },
    pricing: {
      heading: "Simple, Transparent Pricing",
      subheading: "No hidden fees. No surprises. Just great work.",
      tiers: [
        {
          name: "Starter Setup",
          price: "PKR 25,000",
          description: "Get your project properly deployed on modern cloud infrastructure.",
          features: [
            "Vercel or AWS deployment",
            "Domain & SSL configuration",
            "Environment variables setup",
            "Basic monitoring setup",
            "GitHub deployment pipeline",
            "2 weeks post-launch support",
          ],
        },
        {
          name: "Full Infrastructure",
          price: "PKR 60,000",
          badge: "Most Popular",
          description: "Complete cloud setup with CI/CD, monitoring, and databases.",
          features: [
            "All Starter features",
            "Database setup & optimization",
            "Full CI/CD pipeline",
            "Uptime & error monitoring",
            "Auto-scaling configuration",
            "Security hardening",
            "1 month managed support",
          ],
        },
        {
          name: "Managed Cloud",
          price: "PKR 15,000 / month",
          description: "Ongoing management — we handle your cloud so you don't have to.",
          features: [
            "All infrastructure managed by us",
            "24/7 uptime monitoring",
            "Incident response & fixes",
            "Monthly performance reports",
            "Regular security updates",
            "Backup verification",
            "On-call support",
          ],
        },
      ],
    },
    faqs: [
      {
        q: "Which cloud platforms do you work with?",
        a: "Primarily AWS and Vercel — the two most powerful and widely-used platforms. We also work with DigitalOcean, Railway, and Render depending on your specific needs and budget.",
      },
      {
        q: "Will I own my cloud accounts and infrastructure?",
        a: "Yes, always. We work inside your own AWS or cloud accounts — you own everything. We never lock you into our accounts or make you dependent on us.",
      },
      {
        q: "Can you migrate my existing site without downtime?",
        a: "In most cases, yes. We plan migrations carefully — setting up the new environment first, testing thoroughly, then switching over with minimal or zero downtime.",
      },
      {
        q: "How much does cloud hosting cost monthly?",
        a: "For a standard Next.js website, Vercel's free or Pro plan (PKR 5,000–6,000/month) handles most traffic. AWS costs vary by usage — we always give you a clear cost estimate before starting.",
      },
      {
        q: "Do you provide ongoing management after setup?",
        a: "Yes — our Managed Cloud plan covers ongoing monitoring, updates, security patches, and incident response. Most clients prefer this so they never have to think about infrastructure.",
      },
    ],
    cta: {
      heading: "Build Infrastructure That Never Lets You Down",
      subheading: "Stop worrying about servers. Focus on growing your business.",
      primaryCTA: "Set Up My Cloud",
      primaryLink: "/contact",
      secondaryCTA: "WhatsApp Us",
      secondaryLink: "https://wa.me/923212322687",
      note: "Free infrastructure audit • Clear cost estimate upfront • You own everything",
    },
  },
];
